// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://undkdasggriqekbodxsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuZGtkYXNnZ3JpcWVrYm9keHNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMjA0NDYsImV4cCI6MjA2NTY5NjQ0Nn0.6NtAoifc0Q-87zI2zkd3pTRXWvlA_n26nwzORpprSHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);